[package]
name = "timescaledb_toolkit"
version = "0.3.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = []
pg10 = ["pgx/pg10", "pgx-tests/pg10"]
pg11 = ["pgx/pg11", "pgx-tests/pg11"]
pg12 = ["pgx/pg12", "pgx-tests/pg12"]
pg13 = ["pgx/pg13", "pgx-tests/pg13"]
pg_test = ["approx"]

[dependencies]
pgx = {git="https://github.com/JLockerman/pgx.git", branch="timescale"}
pgx-macros = {git="https://github.com/JLockerman/pgx.git", branch="timescale"}
encodings = {path="../crates/encodings"}
flat_serialize = {path="../crates/flat_serialize/flat_serialize"}
flat_serialize_macro = {path="../crates/flat_serialize/flat_serialize_macro"}
tdigest = {path="../crates/t-digest"}
hyperloglogplusplus = {path="../crates/hyperloglogplusplus"}
uddsketch = {path="../crates/udd-sketch"}
counter-agg = {path="../crates/counter-agg"}
stats_agg = {path="../crates/stats-agg"}
time_weighted_average = {path="../crates/time-weighted-average"}
time_series = {path="../crates/time-series"}
asap = {path="../crates/asap"}

approx = {version = "0.4.0", optional = true}
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
paste = "1.0"
rand = "0.8.3"
rand_distr = "0.4.0"
rand_chacha = "0.3.0"

[dev-dependencies]
pgx-tests = {git="https://github.com/JLockerman/pgx.git", branch="timescale"}
approx = "0.4.0"
